from fastapi import FastAPI, BackgroundTasks, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import asyncio
import uuid
import os
import io
import random
import urllib.request
import urllib.parse
import numpy as np
import imageio
from PIL import Image, ImageDraw, ImageFont, ImageFilter

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class WebhookPayload(BaseModel):
    feature_name: str
    description: str
    source: str
    timestamp: str

def install_font():
    font_path = os.path.join(os.path.dirname(__file__), "Inter-Bold.ttf")
    if not os.path.exists(font_path):
        try:
            url = "https://github.com/rsms/inter/raw/master/docs/font-files/Inter-Bold.ttf"
            urllib.request.urlretrieve(url, font_path)
        except:
            pass
    return font_path

def create_poster(feature_name: str, campaign_id: str):
    out_dir = os.path.join(os.path.dirname(__file__), "..", "launchgen-prototype", "public", "generated")
    os.makedirs(out_dir, exist_ok=True)
    
    width, height = 1200, 630
    
    # Generate a UNIQUE AI background for THIS specific feature using Pollinations.ai (FREE, no API key)
    prompt = f"dark premium tech product launch banner, futuristic, {feature_name}, glowing neon orange accents, cinematic lighting, no text, professional marketing creative"
    encoded_prompt = urllib.parse.quote(prompt)
    pollinations_url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width={width}&height={height}&nologo=true"
    
    try:
        # Download AI-generated image unique to this feature
        img_data = urllib.request.urlopen(pollinations_url, timeout=30).read()
        img = Image.open(io.BytesIO(img_data)).convert("RGB")
        img = img.resize((width, height), Image.LANCZOS)
    except:
        # Fallback to local templates if network fails
        templates = [
            os.path.join(os.path.dirname(__file__), "poster_template.png"),
            os.path.join(os.path.dirname(__file__), "poster_template_2.png"),
            os.path.join(os.path.dirname(__file__), "poster_template_3.png"),
            os.path.join(os.path.dirname(__file__), "poster_template_4.png"),
        ]
        template_path = random.choice(templates)
        try:
            img = Image.open(template_path).convert("RGB")
            img = img.resize((width, height), Image.LANCZOS)
        except:
            img = Image.new("RGB", (width, height), color="#09090b")
    
    # Apply dark gradient overlay for text readability
    overlay = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    overlay_draw = ImageDraw.Draw(overlay)
    for y in range(height):
        alpha = int(60 + (y / height) * 160)
        overlay_draw.line([(0, y), (width, y)], fill=(0, 0, 0, alpha))
    img = Image.alpha_composite(img.convert("RGBA"), overlay).convert("RGB")
    
    draw = ImageDraw.Draw(img)
    
    # Load fonts - use Windows system Arial Bold (confirmed available)
    title_font = ImageFont.truetype("arialbd.ttf", 64)
    badge_font = ImageFont.truetype("arialbd.ttf", 22)
    sub_font = ImageFont.truetype("arialbd.ttf", 26)
    
    # Orange accent badge pill
    draw.rounded_rectangle([60, 40, 340, 88], radius=22, fill="#ea580c")
    draw.text((82, 50), "⚡ NEW FEATURE LAUNCH", fill="white", font=badge_font)
    
    # Big feature name with glow/shadow effect for legibility
    for offset in [(3,3), (2,2), (1,1)]:
        draw.text((60+offset[0], 300+offset[1]), feature_name, fill="#000000", font=title_font)
    draw.text((60, 300), feature_name, fill="white", font=title_font)
    
    # Subtitle tagline
    draw.text((60, 400), "10X Faster  •  Pure Automation  •  Zero Friction", fill="#d4d4d8", font=sub_font)
    
    # Bottom bar with branding
    draw.rectangle([0, height-55, width, height], fill=(0, 0, 0, 220))
    draw.text((60, height-42), "GENERATED BY LAUNCHGEN AI", fill="#71717a", font=badge_font)
    draw.text((width-310, height-42), "POWERED BY AI PIPELINE", fill="#f97316", font=badge_font)

    filename = f"poster_{campaign_id}.png"
    filepath = os.path.join(out_dir, filename)
    img.save(filepath)
    return f"/generated/{filename}"

def create_gif(feature_name: str, description: str, campaign_id: str):
    """Generate an animated GIF using ImageIO + FFmpeg with AI-generated backgrounds unique per feature."""
    out_dir = os.path.join(os.path.dirname(__file__), "..", "launchgen-prototype", "public", "generated")
    os.makedirs(out_dir, exist_ok=True)
    
    width, height = 800, 420
    num_frames = 36
    
    # Generate UNIQUE background for THIS feature using Pollinations.ai (different style from poster)
    gif_prompt = f"abstract motion graphics background, {feature_name}, neon light trails, flowing energy particles, dark background, vibrant colors, no text, no people, cinematic"
    encoded = urllib.parse.quote(gif_prompt)
    poll_url = f"https://image.pollinations.ai/prompt/{encoded}?width={width + 80}&height={height + 50}&nologo=true"
    
    try:
        img_data = urllib.request.urlopen(poll_url, timeout=30).read()
        bg_raw = Image.open(io.BytesIO(img_data)).convert("RGB")
        bg_raw = bg_raw.resize((width + 80, height + 50), Image.LANCZOS)
    except:
        # Fallback to local gif backgrounds
        gif_templates = [
            os.path.join(os.path.dirname(__file__), "gif_bg_1.png"),
            os.path.join(os.path.dirname(__file__), "gif_bg_2.png"),
        ]
        try:
            bg_raw = Image.open(random.choice(gif_templates)).convert("RGB")
            bg_raw = bg_raw.resize((width + 80, height + 50), Image.LANCZOS)
        except:
            bg_raw = Image.new("RGB", (width + 80, height + 50), color="#0a0a0a")
    
    # Fonts
    title_font = ImageFont.truetype("arialbd.ttf", 44)
    tag_font = ImageFont.truetype("arialbd.ttf", 15)
    sub_font = ImageFont.truetype("arialbd.ttf", 18)
    stat_font = ImageFont.truetype("arialbd.ttf", 28)
    desc_font = ImageFont.truetype("arial.ttf", 16)
    
    # Trim description for GIF display
    short_desc = (description[:80] + "...") if len(description) > 80 else description
    
    frames = []
    
    for i in range(num_frames):
        progress = (i + 1) / num_frames
        
        # Slow zoom + pan on the AI background
        crop_x = int(40 * progress)
        crop_y = int(25 * (1 - progress))  # Pan upward
        bg_cropped = bg_raw.crop((crop_x, crop_y, crop_x + width, crop_y + height))
        
        frame = bg_cropped.copy()
        draw = ImageDraw.Draw(frame)
        
        # Dark overlay band for text readability
        for y_line in range(80, 360):
            opacity = 200 if 110 < y_line < 330 else 120
            draw.line([(0, y_line), (width, y_line)], fill=(5, 5, 5))
        
        # === PHASE 1: Top progress bar + badge (0-20%) ===
        bar_w = int(width * min(1.0, progress * 1.8))
        draw.rectangle([0, 0, bar_w, 4], fill="#f97316")
        draw.rectangle([0, height-4, int(width * min(1.0, progress * 1.4)), height], fill="#f97316")
        
        # Badge
        if progress > 0.08:
            draw.rounded_rectangle([30, 90, 215, 118], radius=14, fill="#f97316")
            draw.text((42, 95), "JUST SHIPPED", fill="white", font=tag_font)
            draw.rounded_rectangle([225, 90, 310, 118], radius=14, fill="#22c55e")
            draw.text((237, 95), "LIVE", fill="white", font=tag_font)
        
        # === PHASE 2: Feature name typewriter (15-65%) ===
        if progress > 0.15:
            char_pct = min(1.0, (progress - 0.15) / 0.5)
            chars = max(1, int(len(feature_name) * char_pct))
            text = feature_name[:chars]
            draw.text((32, 137), text, fill=(249, 115, 22, 180), font=title_font)
            draw.text((30, 135), text, fill="white", font=title_font)
            if chars < len(feature_name) and i % 3 != 0:
                bbox = draw.textbbox((30, 135), text, font=title_font)
                draw.rectangle([bbox[2]+3, 135, bbox[2]+6, 185], fill="#f97316")
        
        # === PHASE 3: Description typewriter (40-80%) ===
        if progress > 0.4:
            desc_pct = min(1.0, (progress - 0.4) / 0.4)
            desc_chars = max(1, int(len(short_desc) * desc_pct))
            draw.text((30, 200), short_desc[:desc_chars], fill="#a1a1aa", font=desc_font)
        
        # === PHASE 4: Animated stats counters (60-90%) ===
        if progress > 0.6:
            stat_pct = min(1.0, (progress - 0.6) / 0.25)
            
            # Platform count
            plat_count = int(6 * stat_pct)
            draw.text((40, 250), str(plat_count), fill="#f97316", font=stat_font)
            draw.text((75, 258), "Platforms", fill="#71717a", font=tag_font)
            
            # Hashtags count
            hash_count = int(24 * stat_pct)
            draw.text((200, 250), str(hash_count), fill="#22c55e", font=stat_font)
            draw.text((245, 258), "Hashtags", fill="#71717a", font=tag_font)
            
            # Assets count
            asset_count = int(4 * stat_pct)
            draw.text((370, 250), str(asset_count), fill="#60a5fa", font=stat_font)
            draw.text((400, 258), "Creatives", fill="#71717a", font=tag_font)
            
            # Engagement score
            eng_score = int(95 * stat_pct)
            draw.text((540, 250), f"{eng_score}%", fill="#e879f9", font=stat_font)
            draw.text((600, 258), "AI Score", fill="#71717a", font=tag_font)
        
        # === PHASE 5: Campaign status bar slides in (75-100%) ===
        if progress > 0.75:
            slide = min(1.0, (progress - 0.75) / 0.15)
            bar_y = int(height + 50 - (50 + 50) * slide)
            if bar_y < height:
                draw.rectangle([0, bar_y, width, bar_y + 50], fill=(0, 0, 0))
                draw.text((30, bar_y + 15), "CAMPAIGN READY", fill="#22c55e", font=tag_font)
                draw.text((200, bar_y + 15), "|", fill="#3f3f46", font=tag_font)
                draw.text((220, bar_y + 15), "Auto-published to 6 platforms", fill="#a1a1aa", font=tag_font)
                draw.text((width - 150, bar_y + 15), "LAUNCHGEN AI", fill="#f97316", font=tag_font)
        
        frames.append(np.array(frame))
    
    # Hold final frame
    for _ in range(10):
        frames.append(frames[-1].copy())
    
    filename = f"highlight_{campaign_id}.gif"
    filepath = os.path.join(out_dir, filename)
    imageio.mimwrite(filepath, frames, duration=0.08, loop=0)
    return f"/generated/{filename}"

# In-memory store for prototype
campaigns_db = {}

PIPELINE_STEPS = [
    {"id": 1, "name": "Feature Extraction", "status": "pending"},
    {"id": 2, "name": "Target Audience Profiling", "status": "pending"},
    {"id": 3, "name": "Platform Strategy", "status": "pending"},
    {"id": 4, "name": "Copy Generation", "status": "pending"},
    {"id": 5, "name": "Hashtag & Keyword SEO", "status": "pending"},
    {"id": 6, "name": "Creative Generation", "status": "pending"},
    {"id": 7, "name": "Campaign Quality Audit", "status": "pending"},
    {"id": 8, "name": "Packaging Assets", "status": "pending"},
]

async def process_pipeline(campaign_id: str, feature_name: str, description: str):
    campaign = campaigns_db[campaign_id]
    
    for i, step_data in enumerate(PIPELINE_STEPS):
        # Skip Webhook trigger if already done (assuming step 0 is webhook trigger, which is now replaced by Feature Extraction)
        # The new PIPELINE_STEPS starts with "Feature Extraction", so we process all of them.
        
        # Mark current step as processing
        campaign["current_step_index"] = i
        campaign["steps"][i]["status"] = "processing"
        
        # Simulate processing time (5 seconds per step for snappy demo)
        await asyncio.sleep(5.0)
        
        # Complete step
        campaign["steps"][i]["status"] = "completed"
    
    # Finalize state
    campaign["status"] = "campaign_ready"
    
    poster_url = create_poster(feature_name, campaign_id)
    gif_url = create_gif(feature_name, description, campaign_id)
    
    # Generate mock final content based on input
    campaign["result"] = {
        "core_message": f"🚀 SCALING FAST: Why {feature_name} changes the game permanently.",
        "campaign_angle": f"The Ultimate Cheat Code — How {feature_name} gives you superpowers and 10X growth.",
        "keywords": ["ShipIt", "SaaSGrowth", "10xDeveloper", "TechUnicorn", "NextLevel", "HustleAndCode", "VentureCapital", "ProductLedGrowth"],
        "platforms": {
            "linkedin": f"🛑 STOP SCROLLING! We just dropped something MASSIVE. 🤯🚀\n\nSay hello to **{feature_name}**. 🧨\n\nIf you're still doing things the old way, you are falling behind. Here is exactly how we are changing the game forever:\n\n{description}\n\n🔥 **Why this changes EVERYTHING:**\n👉 10X Faster Execution\n👉 Zero friction, pure automation\n👉 The most powerful integration we’ve ever built\n\nI’ve been incredibly proud of the team grinding 24/7 to make this happen. 🍕☕\n\nAre you ready to level up? Drop a '🔥' in the comments below and I'll DM you an exclusive early-access invite! 👇\n\n#BuildInPublic #SaaSGrowth #TechRevolution #10xDeveloper #ShipIt #FounderLife #ProductLaunch",
            "twitter": f"🚨 WE DID IT. 🚨\n\nIntroducing {feature_name} - The absolute cheat code you've been waiting for! 🎮⚡\n\n{description}\n\nStop wasting time. Start scaling automatically.\n\n👇 The link is LIVE. Who's testing it first? 🚀\n#TechLaunch #GrowthHacking #10x #SaaS #ShipIt",
            "discord": f"## 🏆 FEATURE SHIPPED: {feature_name} IS OFFICIALLY LIVE! 🏆\n\n@everyone THE WAIT IS OVER!! 🎉\nWe literally did not sleep last night trying to get this shipped for you all. 💀☕\n\n**What's new?**\n{description}\n\nJump into General chat and tell us what you think! We are giving out 3 months of premium to whoever finds the best use-case for this. LFG!!! 🚀🔥",
            "reddit": f"🚀 We just built {feature_name} so you can fire your manual workflows. Roast us.\n\nHey r/SaaS and r/startups,\n\nWe were so sick of the old manual processes, we spent the last 3 weekends explicitly building **{feature_name}** to automate it entirely.\n\n**The TL;DR:** {description}\n\nWe know it's not perfect yet, but the speed increases we are seeing internally are insane. \n\nWhat do you guys think? Will this actually save you time or is it a gimmick? Brutal feedback welcome. 👇",
            "instagram": f"THE WAIT IS OVER. 🎬✨\n\nMeet {feature_name}. Faster. Smarter. Completely automated.\n\nWe engineered this purely because we were tired of limits. {description}\n\nImagine cutting your workload by 80% today. 🤯\n\n👉 Click the LINK IN BIO to grab your early access!! 🚀\n\n#StartupJourney #TechVibes #Innovation #GrowthHacking #SaaS #ProductLaunch #DeveloperLife #TechTrends",
            "threads": f"Not gonna lie, we just broke our own platform trying to release {feature_name} today. 💀🚀 The sheer volume of traffic is insane. If you hate manual work, {description}. We’re answering questions in the replies right now! 👇🔥"
        },
        "creatives": {
            "poster": poster_url,
            "carousel": 4,
            "video": True,
            "gif": gif_url
        }
    }

@app.post("/api/webhook")
async def receive_webhook(payload: WebhookPayload, background_tasks: BackgroundTasks):
    campaign_id = str(uuid.uuid4())
    
    # Initialize campaign
    steps = [{"name": step["name"], "status": "pending"} for step in PIPELINE_STEPS]
    steps[0]["status"] = "completed" # Webhook trigger is instant
    
    campaigns_db[campaign_id] = {
        "id": campaign_id,
        "feature_name": payload.feature_name,
        "description": payload.description,
        "status": "processing",
        "current_step_index": 1,
        "steps": steps,
        "result": None
    }
    
    background_tasks.add_task(process_pipeline, campaign_id, payload.feature_name, payload.description)
    return {"message": "Webhook received, processing started", "campaign_id": campaign_id}

@app.get("/api/campaigns")
async def get_campaigns():
    # Return as list, newest first
    return {"campaigns": list(campaigns_db.values())[::-1]}

@app.get("/api/campaigns/{campaign_id}")
async def get_campaign(campaign_id: str):
    if campaign_id in campaigns_db:
        return campaigns_db[campaign_id]
    return {"error": "Campaign not found"}, 404

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8001)
